networks:
  flick_network:
    driver: bridge

services:
  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - flick_network
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flick
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flick_network

  gateway:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_PORT=8080
      - CONSUL_AGENT_ADDR=consul:8500
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flick
      - POSTGRES_PORT=5432
    depends_on:
      consul:
        condition: service_started
      postgres:
        condition: service_started
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - flick_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway-service:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "postgres:5432", "-t", "0", "--", "/usr/local/bin/wait-for-it.sh", "consul:8500", "-t", "0", "--", "/usr/local/bin/wait-for-it.sh", "auth-service:50053", "-t", "0", "--", "/usr/local/bin/wait-for-it.sh", "user-service:50051", "-t", "0", "--", "/app/gateway"]

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
    networks:
      - flick_network

  auth-service:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    container_name: auth-service
    volumes:
      - ../../.ca:/etc/ssl/certs/custom
    environment:
      - AUTH_SERVICE_PORT=50053
      - CONSUL_AGENT_ADDR=consul:8500
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flick
      - POSTGRES_PORT=5432
    depends_on:
      - consul
      - postgres
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50053", "-service=auth-service"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - flick_network
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "postgres:5432", "-t", "0", "--", "/app/auth"]
    restart: always

  user-service:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    container_name: user-service
    environment:
      - USER_SERVICE_PORT=50051
      - CONSUL_AGENT_ADDR=consul:8500
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flick
      - POSTGRES_PORT=5432
    depends_on:
      - consul
      - postgres
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051", "-service=user-service"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - flick_network
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "postgres:5432", "-t", "0", "--", "/app/user"]
    restart: always

volumes:
  postgres_data:
