package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.61

import (
	"context"
	"errors"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/flick/backend/services/gateway/internal/graphql/generated"
	"github.com/flick/backend/services/gateway/internal/graphql/model"
	"github.com/flick/backend/services/gateway/internal/middleware"
	user_proto "github.com/flick/backend/services/user/proto"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	identifier := ""
	if input.Username != nil {
		identifier = *input.Username
	} else if input.Email != nil {
		identifier = *input.Email
	} else {
		return nil, errors.New("username or email is required")
	}

	res, err := r.UserServiceClient.Login(ctx, &user_proto.LoginRequest{
		Identifier: identifier,
		Password:   input.Password,
	})
	if err != nil {
		return nil, err
	}
	if res.Error != nil {
		return nil, errors.New(res.Error.Message)
	}

	return &model.AuthPayload{
		Token: res.Token,
		User:  r.userProtoToGql(res.User),
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	displayName := ""
	if input.DisplayName != nil {
		displayName = *input.DisplayName
	}

	res, err := r.UserServiceClient.Register(ctx, &user_proto.RegisterRequest{
		Username:    input.Username,
		Email:       input.Email,
		Password:    input.Password,
		DisplayName: displayName,
	})
	if err != nil {
		return nil, err
	}
	if res.Error != nil {
		return nil, errors.New(res.Error.Message)
	}

	return &model.AuthPayload{
		Token: res.Token,
		User:  r.userProtoToGql(res.User),
	}, nil
}

// CreateTweet is the resolver for the createTweet field.
func (r *mutationResolver) CreateTweet(ctx context.Context, input model.CreateTweetInput) (*model.Tweet, error) {
	panic(fmt.Errorf("not implemented: CreateTweet - createTweet"))
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: CreateComment - createComment"))
}

// LikeTweet is the resolver for the likeTweet field.
func (r *mutationResolver) LikeTweet(ctx context.Context, input model.LikeTweetInput) (*model.Interaction, error) {
	panic(fmt.Errorf("not implemented: LikeTweet - likeTweet"))
}

// UnlikeTweet is the resolver for the unlikeTweet field.
func (r *mutationResolver) UnlikeTweet(ctx context.Context, input model.LikeTweetInput) (*model.Interaction, error) {
	panic(fmt.Errorf("not implemented: UnlikeTweet - unlikeTweet"))
}

// BookmarkTweet is the resolver for the bookmarkTweet field.
func (r *mutationResolver) BookmarkTweet(ctx context.Context, input model.BookmarkTweetInput) (*model.Interaction, error) {
	panic(fmt.Errorf("not implemented: BookmarkTweet - bookmarkTweet"))
}

// UnbookmarkTweet is the resolver for the unbookmarkTweet field.
func (r *mutationResolver) UnbookmarkTweet(ctx context.Context, input model.BookmarkTweetInput) (*model.Interaction, error) {
	panic(fmt.Errorf("not implemented: UnbookmarkTweet - unbookmarkTweet"))
}

// Retweet is the resolver for the retweet field.
func (r *mutationResolver) Retweet(ctx context.Context, input model.RetweetInput) (*model.Interaction, error) {
	panic(fmt.Errorf("not implemented: Retweet - retweet"))
}

// UndoRetweet is the resolver for the undoRetweet field.
func (r *mutationResolver) UndoRetweet(ctx context.Context, input model.RetweetInput) (*model.Interaction, error) {
	panic(fmt.Errorf("not implemented: UndoRetweet - undoRetweet"))
}

// MarkNotificationAsRead is the resolver for the markNotificationAsRead field.
func (r *mutationResolver) MarkNotificationAsRead(ctx context.Context, id string) (*model.Notification, error) {
	panic(fmt.Errorf("not implemented: MarkNotificationAsRead - markNotificationAsRead"))
}

// MarkAllNotificationsAsRead is the resolver for the markAllNotificationsAsRead field.
func (r *mutationResolver) MarkAllNotificationsAsRead(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: MarkAllNotificationsAsRead - markAllNotificationsAsRead"))
}

// CreateConversation is the resolver for the createConversation field.
func (r *mutationResolver) CreateConversation(ctx context.Context, input model.CreateConversationInput) (*model.Conversation, error) {
	panic(fmt.Errorf("not implemented: CreateConversation - createConversation"))
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.CreateMessageInput) (*model.Message, error) {
	panic(fmt.Errorf("not implemented: SendMessage - sendMessage"))
}

// MarkMessageAsRead is the resolver for the markMessageAsRead field.
func (r *mutationResolver) MarkMessageAsRead(ctx context.Context, messageID string) (*model.Message, error) {
	panic(fmt.Errorf("not implemented: MarkMessageAsRead - markMessageAsRead"))
}

// UploadMedia is the resolver for the uploadMedia field.
func (r *mutationResolver) UploadMedia(ctx context.Context, file graphql.Upload) (*model.Media, error) {
	panic(fmt.Errorf("not implemented: UploadMedia - uploadMedia"))
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.User, error) {
	// Gateway log: GraphQL mutation received
	fmt.Printf("[Gateway] UpdateProfile mutation received\n")

	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		fmt.Printf("[Gateway] UpdateProfile unauthorized: no user claims\n")
		return nil, errors.New("unauthorized")
	}
	userID := claims.UserID

	req := &user_proto.UpdateProfileRequest{
		UserId:      userID,
		DisplayName: input.DisplayName,
		Bio:         input.Bio,
		Location:    input.Location,
		Website:     input.Website,
		AvatarUrl:   input.AvatarURL,
		BannerUrl:   input.BannerURL,
	}

	// Gateway log: Calling user service
	fmt.Printf("[Gateway] Calling user-service UpdateProfile for userID: %s\n", userID)

	res, err := r.UserServiceClient.UpdateProfile(ctx, req)
	if err != nil {
		fmt.Printf("[Gateway] User-service call failed: %v\n", err)
		return nil, err
	}
	if res.Error != nil {
		fmt.Printf("[Gateway] User-service returned error: %s\n", res.Error.Message)
		return nil, errors.New(res.Error.Message)
	}

	return r.userProtoToGql(res.User), nil
}

// FollowUser is the resolver for the followUser field.
func (r *mutationResolver) FollowUser(ctx context.Context, userID string) (*model.User, error) {
	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return nil, errors.New("unauthorized")
	}
	followerID := claims.UserID

	res, err := r.UserServiceClient.FollowUser(ctx, &user_proto.FollowUserRequest{
		FollowerId:  followerID,
		FollowingId: userID,
	})
	if err != nil {
		return nil, err
	}
	if res.Error != nil {
		return nil, errors.New(res.Error.Message)
	}

	return r.userProtoToGql(res.User), nil
}

// UnfollowUser is the resolver for the unfollowUser field.
func (r *mutationResolver) UnfollowUser(ctx context.Context, userID string) (*model.User, error) {
	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return nil, errors.New("unauthorized")
	}
	followerID := claims.UserID

	res, err := r.UserServiceClient.UnfollowUser(ctx, &user_proto.UnfollowUserRequest{
		FollowerId:  followerID,
		FollowingId: userID,
	})
	if err != nil {
		return nil, err
	}
	if res.Error != nil {
		return nil, errors.New(res.Error.Message)
	}

	return r.userProtoToGql(res.User), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*string, error) {
	health := "ok"
	return &health, nil
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, username string) (*model.User, error) {
	// Gateway log: GraphQL query received
	fmt.Printf("[Gateway] UserByUsername query received for: %s\n", username)

	res, err := r.UserServiceClient.GetUserByUsername(ctx, &user_proto.GetUserByUsernameRequest{
		Username: username,
	})
	if err != nil {
		fmt.Printf("[Gateway] User-service call failed: %v\n", err)
		return nil, err
	}
	if res.Error != nil {
		fmt.Printf("[Gateway] User-service returned error: %s\n", res.Error.Message)
		return nil, errors.New(res.Error.Message)
	}

	fmt.Printf("[Gateway] UserByUsername resolved successfully\n")
	return r.userProtoToGql(res.User), nil
}

// Tweet is the resolver for the tweet field.
func (r *queryResolver) Tweet(ctx context.Context, id string) (*model.Tweet, error) {
	// Gateway log: GraphQL query received
	fmt.Printf("[Gateway] Tweet query received for: %s\n", id)
	panic(fmt.Errorf("not implemented: Tweet - tweet"))
}

// UserTweets is the resolver for the userTweets field.
func (r *queryResolver) UserTweets(ctx context.Context, username string, first int, after *string) (*model.TweetConnection, error) {
	// Mock implementation: returns an empty list of tweets.
	// Replace with a call to the content service when it's implemented.
	return &model.TweetConnection{
		Edges:    []model.TweetEdge{},
		PageInfo: &model.PageInfo{HasNextPage: false},
	}, nil
}

// HomeFeed is the resolver for the homeFeed field.
func (r *queryResolver) HomeFeed(ctx context.Context, first int, after *string) (*model.TweetConnection, error) {
	panic(fmt.Errorf("not implemented: HomeFeed - homeFeed"))
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, first int, after *string) (*model.NotificationConnection, error) {
	panic(fmt.Errorf("not implemented: Notifications - notifications"))
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context) ([]model.Conversation, error) {
	panic(fmt.Errorf("not implemented: Conversations - conversations"))
}

// Conversation is the resolver for the conversation field.
func (r *queryResolver) Conversation(ctx context.Context, id string) (*model.Conversation, error) {
	panic(fmt.Errorf("not implemented: Conversation - conversation"))
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, conversationID string, first int, after *string) (*model.MessageConnection, error) {
	panic(fmt.Errorf("not implemented: Messages - messages"))
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, input model.SearchInput) (*model.SearchResults, error) {
	panic(fmt.Errorf("not implemented: Search - search"))
}

// TrendingHashtags is the resolver for the trendingHashtags field.
func (r *queryResolver) TrendingHashtags(ctx context.Context, first int) ([]model.Hashtag, error) {
	panic(fmt.Errorf("not implemented: TrendingHashtag - trendingHashtags"))
}

// RecommendedUsers is the resolver for the recommendedUsers field.
func (r *queryResolver) RecommendedUsers(ctx context.Context, first int) ([]model.User, error) {
	// TODO: Implement actual recommendation logic
	// For now, return empty list to prevent panic and allow frontend to work
	return []model.User{}, nil
}

// RecommendedTweets is the resolver for the recommendedTweets field.
func (r *queryResolver) RecommendedTweets(ctx context.Context, first int) (*model.TweetConnection, error) {
	panic(fmt.Errorf("not implemented: RecommendedTweets - recommendedTweets"))
}

// Followers is the resolver for the followers field.
func (r *queryResolver) Followers(ctx context.Context, userID string, first int, after *string) (*model.UserConnection, error) {
	// Gateway log: GraphQL query received
	fmt.Printf("[Gateway] Followers query received for userID: %s\n", userID)

	// TODO: Implement actual followers logic with user service
	// For now, return empty connection to prevent 404 and allow frontend to work
	return &model.UserConnection{
		Edges:    []model.UserEdge{},
		PageInfo: &model.PageInfo{HasNextPage: false},
	}, nil
}

// Following is the resolver for the following field.
func (r *queryResolver) Following(ctx context.Context, userID string, first int, after *string) (*model.UserConnection, error) {
	// Gateway log: GraphQL query received
	fmt.Printf("[Gateway] Following query received for userID: %s\n", userID)

	// TODO: Implement actual following logic with user service
	// For now, return empty connection to prevent 404 and allow frontend to work
	return &model.UserConnection{
		Edges:    []model.UserEdge{},
		PageInfo: &model.PageInfo{HasNextPage: false},
	}, nil
}

// UserReplies is the resolver for the userReplies field.
func (r *queryResolver) UserReplies(ctx context.Context, userID string, first int, after *string) (*model.TweetConnection, error) {
	// Gateway log: GraphQL query received
	fmt.Printf("[Gateway] UserReplies query received for userID: %s\n", userID)

	// TODO: Implement actual user replies logic with content service
	// For now, return empty connection to prevent 404 and allow frontend to work
	return &model.TweetConnection{
		Edges:    []model.TweetEdge{},
		PageInfo: &model.PageInfo{HasNextPage: false},
	}, nil
}

// UserMedia is the resolver for the userMedia field.
func (r *queryResolver) UserMedia(ctx context.Context, userID string, first int, after *string) (*model.TweetConnection, error) {
	// Gateway log: GraphQL query received
	fmt.Printf("[Gateway] UserMedia query received for userID: %s\n", userID)

	// TODO: Implement actual user media logic with content/media service
	// For now, return empty connection to prevent 404 and allow frontend to work
	return &model.TweetConnection{
		Edges:    []model.TweetEdge{},
		PageInfo: &model.PageInfo{HasNextPage: false},
	}, nil
}

// UserLikes is the resolver for the userLikes field.
func (r *queryResolver) UserLikes(ctx context.Context, userID string, first int, after *string) (*model.TweetConnection, error) {
	// Gateway log: GraphQL query received
	fmt.Printf("[Gateway] UserLikes query received for userID: %s\n", userID)

	// TODO: Implement actual user likes logic with interaction service
	// For now, return empty connection to prevent 404 and allow frontend to work
	return &model.TweetConnection{
		Edges:    []model.TweetEdge{},
		PageInfo: &model.PageInfo{HasNextPage: false},
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
