package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/flick/backend/pkg/messagebus"
	content_proto "github.com/flick/backend/services/content/proto"
	"github.com/flick/backend/services/gateway/internal/graphql/generated"
	"github.com/flick/backend/services/gateway/internal/graphql/model"
	"github.com/flick/backend/services/gateway/internal/middleware"
	interaction_proto "github.com/flick/backend/services/interaction/proto"
	media_proto "github.com/flick/backend/services/media/proto"
	user_proto "github.com/flick/backend/services/user/proto"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	identifier := input.Username
	if identifier == "" {
		return nil, errors.New("username is required")
	}

	res, err := r.UserServiceClient.Login(ctx, &user_proto.LoginRequest{
		Identifier: identifier,
		Password:   input.Password,
	})
	if err != nil {
		return nil, err
	}
	if res.Error != nil {
		return nil, errors.New(res.Error.Message)
	}

	return &model.AuthPayload{
		Token: res.Token,
		User:  r.userProtoToGql(res.User),
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	displayName := ""
	if input.DisplayName != nil {
		displayName = *input.DisplayName
	}

	res, err := r.UserServiceClient.Register(ctx, &user_proto.RegisterRequest{
		Username:    input.Username,
		Email:       input.Email,
		Password:    input.Password,
		DisplayName: displayName,
	})
	if err != nil {
		return nil, err
	}
	if res.Error != nil {
		return nil, errors.New(res.Error.Message)
	}

	return &model.AuthPayload{
		Token: res.Token,
		User:  r.userProtoToGql(res.User),
	}, nil
}

// UploadAvatar is the resolver for the uploadAvatar field.
func (r *mutationResolver) UploadAvatar(ctx context.Context, input model.UploadAvatarInput) (*model.MediaUploadResult, error) {
	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return &model.MediaUploadResult{
			FileID:  "",
			FileURL: "",
			Success: false,
			Message: stringPtr("unauthorized"),
		}, nil
	}

	// Create authenticated context for gRPC call
	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return &model.MediaUploadResult{
			FileID:  "",
			FileURL: "",
			Success: false,
			Message: stringPtr("authentication failed"),
		}, nil
	}

	// Read file content
	fileContent, err := io.ReadAll(input.File.File)
	if err != nil {
		return &model.MediaUploadResult{
			FileID:  "",
			FileURL: "",
			Success: false,
			Message: stringPtr("failed to read file"),
		}, nil
	}

	// Call media service
	res, err := r.MediaServiceClient.UploadFile(authCtx, &media_proto.UploadFileRequest{
		UserId:      input.UserID,
		Content:     fileContent,
		Filename:    input.File.Filename,
		ContentType: input.File.ContentType,
		FileType:    "avatar",
	})

	if err != nil {
		return &model.MediaUploadResult{
			FileID:  "",
			FileURL: "",
			Success: false,
			Message: stringPtr(fmt.Sprintf("upload failed: %v", err)),
		}, nil
	}

	return &model.MediaUploadResult{
		FileID:  res.FileId,
		FileURL: res.FileUrl,
		Success: true,
		Message: stringPtr("upload successful"),
	}, nil
}

// UploadBanner is the resolver for the uploadBanner field.
func (r *mutationResolver) UploadBanner(ctx context.Context, input model.UploadBannerInput) (*model.MediaUploadResult, error) {
	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return &model.MediaUploadResult{
			FileID:  "",
			FileURL: "",
			Success: false,
			Message: stringPtr("unauthorized"),
		}, nil
	}

	// Create authenticated context for gRPC call
	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return &model.MediaUploadResult{
			FileID:  "",
			FileURL: "",
			Success: false,
			Message: stringPtr("authentication failed"),
		}, nil
	}

	// Read file content
	fileContent, err := io.ReadAll(input.File.File)
	if err != nil {
		return &model.MediaUploadResult{
			FileID:  "",
			FileURL: "",
			Success: false,
			Message: stringPtr("failed to read file"),
		}, nil
	}

	// Call media service
	res, err := r.MediaServiceClient.UploadFile(authCtx, &media_proto.UploadFileRequest{
		UserId:      input.UserID,
		Content:     fileContent,
		Filename:    input.File.Filename,
		ContentType: input.File.ContentType,
		FileType:    "banner",
	})

	if err != nil {
		return &model.MediaUploadResult{
			FileID:  "",
			FileURL: "",
			Success: false,
			Message: stringPtr(fmt.Sprintf("upload failed: %v", err)),
		}, nil
	}

	return &model.MediaUploadResult{
		FileID:  res.FileId,
		FileURL: res.FileUrl,
		Success: true,
		Message: stringPtr("upload successful"),
	}, nil
}

// UploadPostMedia is the resolver for the uploadPostMedia field.
func (r *mutationResolver) UploadPostMedia(ctx context.Context, input model.UploadPostMediaInput) ([]model.MediaUploadResult, error) {
	fmt.Printf("[Gateway] UploadPostMedia resolver called - START\n")
	fmt.Printf("[Gateway] UploadPostMedia input - UserID: %s, Files count: %d\n", input.UserID, len(input.Files))

	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		fmt.Printf("[Gateway] UploadPostMedia FAILED - no user claims\n")
		return []model.MediaUploadResult{{
			FileID:  "",
			FileURL: "",
			Success: false,
			Message: stringPtr("unauthorized"),
		}}, nil
	}
	fmt.Printf("[Gateway] UploadPostMedia authenticated - UserID: %s\n", claims.UserID)

	// Create authenticated context for gRPC call
	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		fmt.Printf("[Gateway] UploadPostMedia FAILED - auth context creation failed: %v\n", err)
		return []model.MediaUploadResult{{
			FileID:  "",
			FileURL: "",
			Success: false,
			Message: stringPtr("authentication failed"),
		}}, nil
	}
	fmt.Printf("[Gateway] UploadPostMedia auth context created successfully\n")

	var results []model.MediaUploadResult

	for i, file := range input.Files {
		fmt.Printf("[Gateway] UploadPostMedia processing file %d - Filename: %s, ContentType: %s\n", i, file.Filename, file.ContentType)

		// Read file content
		fileContent, err := io.ReadAll(file.File)
		if err != nil {
			fmt.Printf("[Gateway] UploadPostMedia FAILED - file read error for file %d: %v\n", i, err)
			results = append(results, model.MediaUploadResult{
				FileID:  "",
				FileURL: "",
				Success: false,
				Message: stringPtr(fmt.Sprintf("failed to read file %d", i)),
			})
			continue
		}
		fmt.Printf("[Gateway] UploadPostMedia file %d read successfully - Size: %d bytes\n", i, len(fileContent))

		// Get alt text if provided
		altText := ""
		if i < len(input.AltTexts) {
			altText = input.AltTexts[i]
		}
		fmt.Printf("[Gateway] UploadPostMedia file %d alt text: %s\n", i, altText)

		// Call media service
		fmt.Printf("[Gateway] UploadPostMedia calling media service for file %d\n", i)
		res, err := r.MediaServiceClient.UploadFile(authCtx, &media_proto.UploadFileRequest{
			UserId:      input.UserID,
			Content:     fileContent,
			Filename:    file.Filename,
			ContentType: file.ContentType,
			FileType:    "post",
			AltText:     altText,
		})

		if err != nil {
			fmt.Printf("[Gateway] UploadPostMedia FAILED - media service error for file %d: %v\n", i, err)
			userFriendlyMsg := convertErrorToUserMessage(err)
			results = append(results, model.MediaUploadResult{
				FileID:  "",
				FileURL: "",
				Success: false,
				Message: stringPtr(userFriendlyMsg),
			})
			continue
		}

		fmt.Printf("[Gateway] UploadPostMedia SUCCESS - file %d uploaded - FileID: %s, FileURL: %s\n", i, res.FileId, res.FileUrl)
		results = append(results, model.MediaUploadResult{
			FileID:  res.FileId,
			FileURL: res.FileUrl,
			Success: true,
			Message: stringPtr("upload successful"),
		})
	}

	fmt.Printf("[Gateway] UploadPostMedia resolver completed - Results count: %d\n", len(results))
	return results, nil
}

// DeleteMedia is the resolver for the deleteMedia field.
func (r *mutationResolver) DeleteMedia(ctx context.Context, input model.DeleteMediaInput) (bool, error) {
	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return false, errors.New("unauthorized")
	}

	// Create authenticated context for gRPC call
	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication failed: %v", err)
	}

	// Call media service
	_, err = r.MediaServiceClient.DeleteFile(authCtx, &media_proto.DeleteFileRequest{
		FileUrl: input.FileURL,
		UserId:  claims.UserID,
	})

	if err != nil {
		return false, fmt.Errorf("delete failed: %v", err)
	}

	return true, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	fmt.Printf("[Gateway] CreatePost mutation received\n")

	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		fmt.Printf("[Gateway] CreatePost unauthorized: no user claims\n")
		return nil, errors.New("unauthorized")
	}

	// Debug: Log input values
	fmt.Printf("[Gateway] CreatePost input:\n")
	fmt.Printf("  Content: %s\n", input.Content)
	fmt.Printf("  UserID: %s\n", claims.UserID)

	req := &content_proto.CreatePostRequest{
		UserId:  claims.UserID,
		Content: input.Content,
	}

	if input.Visibility != nil {
		req.Visibility = string(*input.Visibility)
	}
	if input.ReplyPermission != nil {
		req.ReplyPermission = string(*input.ReplyPermission)
	}
	if input.ParentID != nil {
		req.ParentId = *input.ParentID
	}
	if input.MediaUrls != nil {
		req.MediaUrls = input.MediaUrls
	}
	if input.Tags != nil {
		req.Tags = input.Tags
	}

	fmt.Printf("[Gateway] Calling content-service CreatePost\n")

	// Create authenticated gRPC context
	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.ContentServiceClient.CreatePost(authCtx, req)
	if err != nil {
		fmt.Printf("[Gateway] Content-service call failed: %v\n", err)
		return nil, err
	}

	if res.Error != nil {
		fmt.Printf("[Gateway] Content-service returned error: %s\n", res.Error.Message)
		return nil, errors.New(res.Error.Message)
	}

	fmt.Printf("[Gateway] Post created successfully: %s\n", res.Post.Id)

	// Convert proto to GraphQL model
	gqlPost := r.postProtoToGql(res.Post)
	fmt.Printf("[Gateway] Converted GraphQL post ID: %s\n", gqlPost.ID)
	fmt.Printf("[Gateway] Converted GraphQL post Content: %s\n", gqlPost.Content)
	fmt.Printf("[Gateway] Converted GraphQL post Author ID: %s\n", gqlPost.Author.ID)
	fmt.Printf("[Gateway] Converted GraphQL post Stats: %+v\n", gqlPost.Stats)

	return gqlPost, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, postID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeletePost - deletePost"))
}

// CreateReply is the resolver for the createReply field.
func (r *mutationResolver) CreateReply(ctx context.Context, input model.CreateReplyInput) (*model.Post, error) {
	fmt.Printf("[Gateway] CreateReply mutation received for post %s\n", input.PostID)

	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Prepare the create post request with parent ID to make it a reply
	req := &content_proto.CreatePostRequest{
		UserId:   claims.UserID,
		Content:  input.Content,
		ParentId: input.PostID, // This makes it a reply
	}

	// Add media URLs if provided
	if input.MediaUrls != nil {
		req.MediaUrls = input.MediaUrls
	}

	// Call content service to create the reply
	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.ContentServiceClient.CreatePost(authCtx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to create reply: %w", err)
	}
	if res.Error != nil {
		return nil, fmt.Errorf("content service error: %s", res.Error.Message)
	}

	// Convert proto to GraphQL model
	return r.postProtoToGql(res.Post), nil
}

// DeleteReply is the resolver for the deleteReply field.
func (r *mutationResolver) DeleteReply(ctx context.Context, replyID string) (bool, error) {
	fmt.Printf("[Gateway] DeleteReply mutation received for reply %s\n", replyID)

	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return false, fmt.Errorf("user not authenticated")
	}

	// Call content service to delete the reply
	res, err := r.ContentServiceClient.DeleteReply(ctx, &content_proto.DeleteReplyRequest{
		ReplyId: replyID,
		UserId:  claims.UserID,
	})
	if err != nil {
		return false, fmt.Errorf("failed to delete reply: %w", err)
	}
	if res.Error != nil {
		return false, fmt.Errorf("content service error: %s", res.Error.Message)
	}

	return res.Success, nil
}

// LikePost is the resolver for the likePost field.
func (r *mutationResolver) LikePost(ctx context.Context, input model.LikePostInput) (*model.Interaction, error) {
	fmt.Printf("[Gateway] LikePost mutation received for post %s\n", input.PostID)

	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Call interaction service to like the post
	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.InteractionServiceClient.LikePost(authCtx, &interaction_proto.LikePostRequest{
		PostId: input.PostID,
		UserId: claims.UserID,
	})
	if err != nil {
		fmt.Printf("[Gateway] LikePost failed: %v\n", err)
		return nil, fmt.Errorf("failed to like post: %w", err)
	}
	if res.Error != nil {
		fmt.Printf("[Gateway] LikePost error: %s\n", res.Error.Message)
		return nil, errors.New(res.Error.Message)
	}

	fmt.Printf("[Gateway] LikePost successful: liked=%v, count=%d\n", res.IsLiked, res.LikeCount)

	return &model.Interaction{
		IsLiked:   res.IsLiked,
		LikeCount: int(res.LikeCount),
	}, nil
}

// UnlikePost is the resolver for the unlikePost field.
func (r *mutationResolver) UnlikePost(ctx context.Context, input model.LikePostInput) (*model.Interaction, error) {
	fmt.Printf("[Gateway] UnlikePost mutation received for post %s\n", input.PostID)

	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Call interaction service to unlike the post
	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.InteractionServiceClient.UnlikePost(authCtx, &interaction_proto.UnlikePostRequest{
		PostId: input.PostID,
		UserId: claims.UserID,
	})
	if err != nil {
		fmt.Printf("[Gateway] UnlikePost failed: %v\n", err)
		return nil, fmt.Errorf("failed to unlike post: %w", err)
	}
	if res.Error != nil {
		fmt.Printf("[Gateway] UnlikePost error: %s\n", res.Error.Message)
		return nil, errors.New(res.Error.Message)
	}

	fmt.Printf("[Gateway] UnlikePost successful: liked=%v, count=%d\n", res.IsLiked, res.LikeCount)

	return &model.Interaction{
		IsLiked:   res.IsLiked,
		LikeCount: int(res.LikeCount),
	}, nil
}

// BookmarkPost is the resolver for the bookmarkPost field.
func (r *mutationResolver) BookmarkPost(ctx context.Context, input model.BookmarkPostInput) (*model.Interaction, error) {
	panic(fmt.Errorf("not implemented: BookmarkPost - bookmarkPost"))
}

// UnbookmarkPost is the resolver for the unbookmarkPost field.
func (r *mutationResolver) UnbookmarkPost(ctx context.Context, input model.BookmarkPostInput) (*model.Interaction, error) {
	panic(fmt.Errorf("not implemented: UnbookmarkPost - unbookmarkPost"))
}

// Repost is the resolver for the repost field.
func (r *mutationResolver) Repost(ctx context.Context, input model.RepostInput) (*model.Interaction, error) {
	panic(fmt.Errorf("not implemented: Repost - repost"))
}

// UndoRepost is the resolver for the undoRepost field.
func (r *mutationResolver) UndoRepost(ctx context.Context, input model.RepostInput) (*model.Interaction, error) {
	panic(fmt.Errorf("not implemented: UndoRepost - undoRepost"))
}

// CreateConversation is the resolver for the createConversation field.
func (r *mutationResolver) CreateConversation(ctx context.Context, input model.CreateConversationInput) (*model.Conversation, error) {
	panic(fmt.Errorf("not implemented: CreateConversation - createConversation"))
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.CreateMessageInput) (*model.Message, error) {
	panic(fmt.Errorf("not implemented: SendMessage - sendMessage"))
}

// MarkMessageAsRead is the resolver for the markMessageAsRead field.
func (r *mutationResolver) MarkMessageAsRead(ctx context.Context, messageID string) (*model.Message, error) {
	panic(fmt.Errorf("not implemented: MarkMessageAsRead - markMessageAsRead"))
}

// MarkNotificationAsRead is the resolver for the markNotificationAsRead field.
func (r *mutationResolver) MarkNotificationAsRead(ctx context.Context, id string) (*model.Notification, error) {
	panic(fmt.Errorf("not implemented: MarkNotificationAsRead - markNotificationAsRead"))
}

// MarkAllNotificationsAsRead is the resolver for the markAllNotificationsAsRead field.
func (r *mutationResolver) MarkAllNotificationsAsRead(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: MarkAllNotificationsAsRead - markAllNotificationsAsRead"))
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.User, error) {
	// Gateway log: GraphQL mutation received
	fmt.Printf("[Gateway] UpdateProfile mutation received\n")

	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		fmt.Printf("[Gateway] UpdateProfile unauthorized: no user claims\n")
		return nil, errors.New("unauthorized")
	}
	userID := claims.UserID

	// Debug: Log claims details
	fmt.Printf("[Gateway] Claims details:\n")
	fmt.Printf("  UserID: '%s'\n", claims.UserID)
	fmt.Printf("  Username: '%s'\n", claims.Username)
	fmt.Printf("  Email: '%s'\n", claims.Email)

	// Debug: Log input values
	fmt.Printf("[Gateway] UpdateProfile input values:\n")
	fmt.Printf("  DisplayName: %v\n", input.DisplayName)
	fmt.Printf("  Bio: %v\n", input.Bio)
	fmt.Printf("  Location: %v\n", input.Location)
	fmt.Printf("  Website: %v\n", input.Website)
	fmt.Printf("  AvatarURL: %v\n", input.AvatarURL)
	fmt.Printf("  BannerURL: %v\n", input.BannerURL)

	req := &user_proto.UpdateProfileRequest{
		UserId:      userID,
		DisplayName: input.DisplayName,
		Bio:         input.Bio,
		Location:    input.Location,
		Website:     input.Website,
		AvatarUrl:   input.AvatarURL,
		BannerUrl:   input.BannerURL,
	}

	// Gateway log: Calling user service
	fmt.Printf("[Gateway] Calling user-service UpdateProfile for userID: %s\n", userID)

	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.UserServiceClient.UpdateProfile(authCtx, req)
	if err != nil {
		fmt.Printf("[Gateway] User-service call failed: %v\n", err)
		return nil, err
	}
	if res.Error != nil {
		fmt.Printf("[Gateway] User-service returned error: %s\n", res.Error.Message)
		return nil, errors.New(res.Error.Message)
	}

	return r.userProtoToGql(res.User), nil
}

// FollowUser is the resolver for the followUser field.
func (r *mutationResolver) FollowUser(ctx context.Context, userID string) (*model.User, error) {
	fmt.Printf("[Gateway] FollowUser mutation received for userID: %s\n", userID)

	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		fmt.Printf("[Gateway] FollowUser unauthorized: no user claims found in context\n")
		return nil, errors.New("unauthorized")
	}
	followerID := claims.UserID
	fmt.Printf("[Gateway] FollowUser authorized for follower: %s, followee: %s\n", followerID, userID)

	// 调用interaction服务创建关注关系
	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return nil, err
	}
	followRes, err := r.InteractionServiceClient.CreateFollow(authCtx, &interaction_proto.CreateFollowRequest{
		FollowerId: followerID,
		FolloweeId: userID,
	})
	if err != nil {
		return nil, err
	}
	if followRes.Error != nil {
		return nil, errors.New(followRes.Error.Message)
	}

	// 调用用户服务更新关注者计数
	_, err = r.UserServiceClient.FollowUser(authCtx, &user_proto.FollowUserRequest{
		FollowerId:  followerID,
		FollowingId: userID,
	})
	if err != nil {
		fmt.Printf("[Gateway] Warning: Failed to update follower counts: %v\n", err)
		// Continue execution even if count update fails
	}

	// 获取被关注用户的信息返回
	userRes, err := r.UserServiceClient.GetUser(ctx, &user_proto.GetUserRequest{
		UserId: userID,
	})
	if err != nil {
		return nil, err
	}
	if userRes.Error != nil {
		return nil, errors.New(userRes.Error.Message)
	}

	// 设置关注状态为true，因为刚刚执行了关注操作
	user := userRes.User
	user.IsFollowing = true

	return r.userProtoToGql(user), nil
}

// UnfollowUser is the resolver for the unfollowUser field.
func (r *mutationResolver) UnfollowUser(ctx context.Context, userID string) (*model.User, error) {
	fmt.Printf("[Gateway] UnfollowUser mutation received for userID: %s\n", userID)

	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		fmt.Printf("[Gateway] UnfollowUser unauthorized: no user claims found in context\n")
		return nil, errors.New("unauthorized")
	}
	followerID := claims.UserID
	fmt.Printf("[Gateway] UnfollowUser authorized for follower: %s, followee: %s\n", followerID, userID)

	// 调用interaction服务删除关注关系
	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return nil, err
	}
	unfollowRes, err := r.InteractionServiceClient.DeleteFollow(authCtx, &interaction_proto.DeleteFollowRequest{
		FollowerId: followerID,
		FolloweeId: userID,
	})
	if err != nil {
		return nil, err
	}
	if unfollowRes.Error != nil {
		return nil, errors.New(unfollowRes.Error.Message)
	}

	// 调用用户服务更新关注者计数
	_, err = r.UserServiceClient.UnfollowUser(authCtx, &user_proto.UnfollowUserRequest{
		FollowerId:  followerID,
		FollowingId: userID,
	})
	if err != nil {
		fmt.Printf("[Gateway] Warning: Failed to update follower counts: %v\n", err)
		// Continue execution even if count update fails
	}

	// 获取被取消关注用户的信息返回
	userRes, err := r.UserServiceClient.GetUser(ctx, &user_proto.GetUserRequest{
		UserId: userID,
	})
	if err != nil {
		return nil, err
	}
	if userRes.Error != nil {
		return nil, errors.New(userRes.Error.Message)
	}

	// 设置关注状态为false，因为刚刚执行了取消关注操作
	user := userRes.User
	user.IsFollowing = false

	return r.userProtoToGql(user), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*string, error) {
	health := "OK"
	return &health, nil
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, username string) (*model.User, error) {
	fmt.Printf("[Gateway] UserByUsername query received for username: %s\n", username)

	res, err := r.UserServiceClient.GetUserByUsername(ctx, &user_proto.GetUserByUsernameRequest{
		Username: username,
	})
	if err != nil {
		return nil, err
	}
	if res.Error != nil {
		return nil, errors.New(res.Error.Message)
	}
	if res.User == nil {
		return nil, nil
	}

	user := res.User

	// Check if current user is following this user
	claims := middleware.GetUserClaims(ctx)
	if claims != nil {
		if claims.UserID == user.Id {
			// Viewing own profile - don't show follow button
			user.IsFollowing = false
			fmt.Printf("[Gateway] UserByUsername viewing own profile (%s), setting isFollowing to false\n", claims.UserID)
		} else {
			// Viewing someone else's profile - check actual follow status
			fmt.Printf("[Gateway] UserByUsername checking follow status for follower: %s, followee: %s\n", claims.UserID, user.Id)

			followRes, err := r.InteractionServiceClient.IsFollowing(ctx, &interaction_proto.IsFollowingRequest{
				FollowerId: claims.UserID,
				FolloweeId: user.Id,
			})
			if err != nil {
				fmt.Printf("[Gateway] UserByUsername follow check failed: %v\n", err)
				// Don't fail the query, just set isFollowing to false
				user.IsFollowing = false
			} else if followRes.Error != nil {
				fmt.Printf("[Gateway] UserByUsername follow check error: %s\n", followRes.Error.Message)
				user.IsFollowing = false
			} else {
				user.IsFollowing = followRes.IsFollowing
				fmt.Printf("[Gateway] UserByUsername follow status result: %v for follower %s -> followee %s\n", user.IsFollowing, claims.UserID, user.Id)
			}
		}
	} else {
		// Not authenticated - don't show follow button
		user.IsFollowing = false
		fmt.Printf("[Gateway] UserByUsername no authentication, setting isFollowing to false\n")
	}

	return r.userProtoToGql(user), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	res, err := r.ContentServiceClient.GetPost(ctx, &content_proto.GetPostRequest{
		PostId: id,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get post: %w", err)
	}
	if res.Error != nil {
		return nil, errors.New(res.Error.Message)
	}

	return r.postProtoToGql(res.Post), nil
}

// UserPosts is the resolver for the userPosts field.
func (r *queryResolver) UserPosts(ctx context.Context, username string, first int, after *string) (*model.PostConnection, error) {
	fmt.Printf("[Gateway] UserPosts query received for username: %s, first: %d\n", username, first)

	// 通过用户服务获取用户ID
	fmt.Printf("[Gateway] UserPosts calling user-service GetUserByUsername\n")
	userRes, err := r.UserServiceClient.GetUserByUsername(ctx, &user_proto.GetUserByUsernameRequest{
		Username: username,
	})
	if err != nil {
		fmt.Printf("[Gateway] UserPosts user-service call failed: %v\n", err)
		return nil, fmt.Errorf("failed to get user by username: %w", err)
	}
	if userRes.Error != nil {
		fmt.Printf("[Gateway] UserPosts user-service returned error: %s\n", userRes.Error.Message)
		return nil, errors.New(userRes.Error.Message)
	}
	if userRes.User == nil {
		fmt.Printf("[Gateway] UserPosts user not found: %s\n", username)
		return nil, fmt.Errorf("user not found: %s", username)
	}

	fmt.Printf("[Gateway] UserPosts found user ID: %s for username: %s\n", userRes.User.Id, username)

	// 获取当前请求用户ID
	claims := middleware.GetUserClaims(ctx)
	requestingUserId := ""
	if claims != nil {
		requestingUserId = claims.UserID
	}

	// 处理分页游标
	cursor := ""
	if after != nil {
		cursor = *after
	}

	// 使用真实的用户ID获取帖子
	fmt.Printf("[Gateway] UserPosts calling content-service GetUserPosts for user: %s, requesting user: %s, cursor: %s\n", userRes.User.Id, requestingUserId, cursor)

	// Try to create authenticated context, but fallback to regular context if no auth
	callCtx := ctx
	if middleware.GetTokenFromContext(ctx) != "" {
		authCtx, err := r.createAuthenticatedContext(ctx)
		if err == nil {
			callCtx = authCtx
		}
	}

	res, err := r.ContentServiceClient.GetUserPosts(callCtx, &content_proto.GetUserPostsRequest{
		UserId:           userRes.User.Id,
		RequestingUserId: requestingUserId,
		Limit:            int32(first),
		Cursor:           cursor,
	})
	if err != nil {
		fmt.Printf("[Gateway] UserPosts content-service call failed: %v\n", err)
		return nil, fmt.Errorf("failed to get user posts: %w", err)
	}
	if res.Error != nil {
		fmt.Printf("[Gateway] UserPosts content-service returned error: %s\n", res.Error.Message)
		return nil, errors.New(res.Error.Message)
	}

	fmt.Printf("[Gateway] UserPosts got %d posts from content-service\n", len(res.Posts))

	// 转换为GraphQL连接类型
	edges := make([]model.PostEdge, len(res.Posts))
	for i, post := range res.Posts {
		fmt.Printf("[Gateway] UserPosts converting post %d: ID=%s, Content=%s\n", i, post.Id, post.Content[:min(50, len(post.Content))])
		edges[i] = model.PostEdge{
			Node:   r.postProtoToGql(post),
			Cursor: post.Id, // 简化处理，使用ID作为cursor
		}
	}

	fmt.Printf("[Gateway] UserPosts returning %d edges\n", len(edges))

	// 计算 endCursor
	var endCursor *string
	if len(edges) > 0 && res.HasMore {
		lastCursor := edges[len(edges)-1].Cursor
		endCursor = &lastCursor
		fmt.Printf("[Gateway] UserPosts setting endCursor: %s\n", lastCursor)
	}

	return &model.PostConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: res.HasMore,
			EndCursor:   endCursor,
		},
	}, nil
}

// Timeline is the resolver for the timeline field.
func (r *queryResolver) Timeline(ctx context.Context, first int, after *string) (*model.PostConnection, error) {
	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return nil, errors.New("unauthorized")
	}

	cursor := ""
	if after != nil {
		cursor = *after
	}

	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.ContentServiceClient.GetTimeline(authCtx, &content_proto.GetTimelineRequest{
		UserId: claims.UserID,
		Limit:  int32(first),
		Cursor: cursor, // 简化处理
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get timeline: %w", err)
	}
	if res.Error != nil {
		return nil, errors.New(res.Error.Message)
	}

	// 转换为GraphQL连接类型
	edges := make([]model.PostEdge, len(res.Posts))
	for i, post := range res.Posts {
		edges[i] = model.PostEdge{
			Node:   r.postProtoToGql(post),
			Cursor: post.Id,
		}
	}

	return &model.PostConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: len(res.Posts) == int(first),
			EndCursor:   nil,
		},
	}, nil
}

// FollowingTimeline is the resolver for the followingTimeline field.
func (r *queryResolver) FollowingTimeline(ctx context.Context, first int, after *string) (*model.PostConnection, error) {
	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return nil, errors.New("unauthorized")
	}

	cursor := ""
	if after != nil {
		cursor = *after
	}

	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.ContentServiceClient.GetFollowingTimeline(authCtx, &content_proto.GetTimelineRequest{
		UserId: claims.UserID,
		Limit:  int32(first),
		Cursor: cursor,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get following timeline: %w", err)
	}
	if res.Error != nil {
		return nil, errors.New(res.Error.Message)
	}

	// 转换为GraphQL连接类型
	edges := make([]model.PostEdge, len(res.Posts))
	for i, post := range res.Posts {
		edges[i] = model.PostEdge{
			Node:   r.postProtoToGql(post),
			Cursor: post.Id,
		}
	}

	return &model.PostConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: len(res.Posts) == int(first),
			EndCursor:   nil,
		},
	}, nil
}

// CheckReplyPermission is the resolver for the checkReplyPermission field.
func (r *queryResolver) CheckReplyPermission(ctx context.Context, postID string) (bool, error) {
	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		return false, errors.New("unauthorized")
	}

	res, err := r.ContentServiceClient.CheckReplyPermission(ctx, &content_proto.CheckReplyPermissionRequest{
		PostId: postID,
		UserId: claims.UserID,
	})
	if err != nil {
		return false, fmt.Errorf("failed to check reply permission: %w", err)
	}
	if res.Error != nil {
		return false, errors.New(res.Error.Message)
	}

	return res.CanReply, nil
}

// UserReplies is the resolver for the userReplies field.
func (r *queryResolver) UserReplies(ctx context.Context, userID string, first int, after *string) (*model.PostConnection, error) {
	// Mock implementation: returns an empty list of replies.
	// Replace with a call to the content service when it's implemented.
	return &model.PostConnection{
		Edges:    []model.PostEdge{},
		PageInfo: &model.PageInfo{HasNextPage: false},
	}, nil
}

// UserMedia is the resolver for the userMedia field.
func (r *queryResolver) UserMedia(ctx context.Context, userID string, first int, after *string) (*model.PostConnection, error) {
	// Mock implementation: returns an empty list of media posts.
	// Replace with a call to the content service when it's implemented.
	return &model.PostConnection{
		Edges:    []model.PostEdge{},
		PageInfo: &model.PageInfo{HasNextPage: false},
	}, nil
}

// UserLikes is the resolver for the userLikes field.
func (r *queryResolver) UserLikes(ctx context.Context, userID string, first int, after *string) (*model.PostConnection, error) {
	// Mock implementation: returns an empty list of liked posts.
	// Replace with a call to the content service when it's implemented.
	return &model.PostConnection{
		Edges:    []model.PostEdge{},
		PageInfo: &model.PageInfo{HasNextPage: false},
	}, nil
}

// HomeFeed is the resolver for the homeFeed field.
func (r *queryResolver) HomeFeed(ctx context.Context, first int, after *string) (*model.PostConnection, error) {
	fmt.Printf("[Gateway] HomeFeed query received with first: %d\n", first)

	claims := middleware.GetUserClaims(ctx)
	if claims == nil {
		fmt.Printf("[Gateway] HomeFeed unauthorized: no user claims\n")
		return nil, fmt.Errorf("unauthorized")
	}

	fmt.Printf("[Gateway] HomeFeed calling content-service GetTimeline for user: %s\n", claims.UserID)

	// Create authenticated context for gRPC call
	authCtx, err := r.createAuthenticatedContext(ctx)
	if err != nil {
		return nil, err
	}

	// 调用内容服务获取时间线
	res, err := r.ContentServiceClient.GetTimeline(authCtx, &content_proto.GetTimelineRequest{
		UserId: claims.UserID,
		Limit:  int32(first),
		Cursor: "", // 简化处理
	})
	if err != nil {
		fmt.Printf("[Gateway] HomeFeed content-service call failed: %v\n", err)
		return nil, fmt.Errorf("failed to get timeline: %w", err)
	}
	if res.Error != nil {
		fmt.Printf("[Gateway] HomeFeed content-service returned error: %s\n", res.Error.Message)
		return nil, errors.New(res.Error.Message)
	}

	fmt.Printf("[Gateway] HomeFeed got %d posts from content-service\n", len(res.Posts))

	// 转换为GraphQL连接类型
	edges := make([]model.PostEdge, len(res.Posts))
	for i, post := range res.Posts {
		edges[i] = model.PostEdge{
			Node:   r.postProtoToGql(post),
			Cursor: post.Id,
		}
	}

	return &model.PostConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: res.HasMore,
			EndCursor:   nil,
		},
	}, nil
}

// PostReplies is the resolver for the postReplies field.
func (r *queryResolver) PostReplies(ctx context.Context, postID string, first int, after *string) (*model.PostConnection, error) {
	fmt.Printf("[Gateway] PostReplies query received for post %s\n", postID)

	// Prepare the request
	req := &content_proto.GetPostRepliesRequest{
		PostId: postID,
		Limit:  int32(first),
	}
	if after != nil {
		req.Cursor = *after
	}

	// Call content service
	res, err := r.ContentServiceClient.GetPostReplies(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get post replies: %w", err)
	}
	if res.Error != nil {
		return nil, fmt.Errorf("content service error: %s", res.Error.Message)
	}

	// Convert posts to edges with parent post data
	edges := make([]model.PostEdge, len(res.Replies))
	for i, post := range res.Replies {
		gqlPost := r.postProtoToGql(post)

		// Handle parent post data based on reply level
		if post.ParentId != "" {
			if post.ReplyLevel == 2 {
				// For level 2 replies, try to get the original replied user via ReplyMention
				replyMentionReq := &content_proto.GetReplyMentionRequest{
					ReplyId: post.Id,
				}
				replyMentionRes, err := r.ContentServiceClient.GetReplyMention(ctx, replyMentionReq)
				if err == nil && replyMentionRes.ReplyMention != nil {
					// Get the original replied user info
					userReq := &user_proto.GetUserRequest{
						UserId: replyMentionRes.ReplyMention.MentionedUserId,
					}
					userRes, err := r.UserServiceClient.GetUser(ctx, userReq)
					if err == nil && userRes.User != nil {
						// Create a virtual parent post with the original replied user
						gqlPost.ParentPost = &model.Post{
							ID: replyMentionRes.ReplyMention.MentionedUserId, // Use user ID as placeholder
							Author: &model.User{
								ID:          userRes.User.Id,
								Username:    userRes.User.Username,
								DisplayName: &userRes.User.DisplayName,
							},
							ReplyLevel: 1, // Mark as level 1 for display purposes
						}
						fmt.Printf("[Gateway] Created virtual parentPost for level 2 reply %s -> original user %s\n",
							post.Id, userRes.User.Username)
					}
				}

				// Fallback: use actual parent post if ReplyMention lookup fails
				if gqlPost.ParentPost == nil {
					parentReq := &content_proto.GetPostRequest{
						PostId: post.ParentId,
					}
					parentRes, err := r.ContentServiceClient.GetPost(ctx, parentReq)
					if err == nil && parentRes.Post != nil {
						gqlPost.ParentPost = r.postProtoToGql(parentRes.Post)
						fmt.Printf("[Gateway] Fallback: used actual parent post for level 2 reply %s\n", post.Id)
					}
				}
			} else {
				// For level 1 replies, use actual parent post
				parentReq := &content_proto.GetPostRequest{
					PostId: post.ParentId,
				}
				parentRes, err := r.ContentServiceClient.GetPost(ctx, parentReq)
				if err == nil && parentRes.Post != nil {
					gqlPost.ParentPost = r.postProtoToGql(parentRes.Post)
					fmt.Printf("[Gateway] Populated parentPost for level 1 reply %s -> parent %s (author: %s)\n",
						post.Id, parentRes.Post.Id, parentRes.Post.Author.Username)
				} else {
					fmt.Printf("[Gateway] Failed to get parent post %s for reply %s: %v\n", post.ParentId, post.Id, err)
				}
			}
		}

		edges[i] = model.PostEdge{
			Node:   gqlPost,
			Cursor: post.CreatedAt,
		}
	}

	// Build page info
	pageInfo := &model.PageInfo{
		HasNextPage: res.HasMore,
	}
	if res.NextCursor != "" {
		pageInfo.EndCursor = &res.NextCursor
	}

	return &model.PostConnection{
		Edges:    edges,
		PageInfo: pageInfo,
	}, nil
}

// ConversationThread is the resolver for the conversationThread field.
func (r *queryResolver) ConversationThread(ctx context.Context, rootID string, first int, after *string) (*model.PostConnection, error) {
	fmt.Printf("[Gateway] ConversationThread query received for root %s\n", rootID)

	// Prepare the request
	req := &content_proto.GetConversationThreadRequest{
		RootId: rootID,
		Limit:  int32(first),
	}
	if after != nil {
		req.Cursor = *after
	}

	// Call content service
	res, err := r.ContentServiceClient.GetConversationThread(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get conversation thread: %w", err)
	}
	if res.Error != nil {
		return nil, fmt.Errorf("content service error: %s", res.Error.Message)
	}

	// Convert posts to edges
	edges := make([]model.PostEdge, len(res.Posts))
	for i, post := range res.Posts {
		edges[i] = model.PostEdge{
			Node:   r.postProtoToGql(post),
			Cursor: post.CreatedAt,
		}
	}

	// Build page info
	pageInfo := &model.PageInfo{
		HasNextPage: res.HasMore,
	}
	if res.NextCursor != "" {
		pageInfo.EndCursor = &res.NextCursor
	}

	return &model.PostConnection{
		Edges:    edges,
		PageInfo: pageInfo,
	}, nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, first int, after *string) (*model.NotificationConnection, error) {
	fmt.Printf("[Gateway] Notifications query received\n")

	// TODO: Implement actual notifications fetching from notification service
	// For now, return empty connection to prevent 422 error
	return &model.NotificationConnection{
		Edges: []model.NotificationEdge{},
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			EndCursor:   nil,
		},
	}, nil
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context) ([]model.Conversation, error) {
	fmt.Printf("[Gateway] Conversations query received\n")

	// TODO: Implement actual conversations fetching from messages service
	// For now, return empty list to prevent panic
	return []model.Conversation{}, nil
}

// Conversation is the resolver for the conversation field.
func (r *queryResolver) Conversation(ctx context.Context, id string) (*model.Conversation, error) {
	fmt.Printf("[Gateway] Conversation query received for ID: %s\n", id)

	// TODO: Implement actual conversation fetching from messages service
	// For now, return nil to prevent panic
	return nil, fmt.Errorf("conversation not found")
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, conversationID string, first int, after *string) (*model.MessageConnection, error) {
	fmt.Printf("[Gateway] Messages query received for conversation: %s\n", conversationID)

	// TODO: Implement actual messages fetching from messages service
	// For now, return empty connection to prevent panic
	return &model.MessageConnection{
		Edges: []model.MessageEdge{},
		PageInfo: &model.PageInfo{
			HasNextPage: false,
			EndCursor:   nil,
		},
	}, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, input model.SearchInput) (*model.SearchResults, error) {
	panic(fmt.Errorf("not implemented: Search - search"))
}

// TrendingHashtags is the resolver for the trendingHashtags field.
func (r *queryResolver) TrendingHashtags(ctx context.Context, first int) ([]model.Hashtag, error) {
	panic(fmt.Errorf("not implemented: TrendingHashtag - trendingHashtags"))
}

// RecommendedUsers is the resolver for the recommendedUsers field.
func (r *queryResolver) RecommendedUsers(ctx context.Context, first int) ([]model.User, error) {
	// TODO: Implement actual recommendation logic
	// For now, return empty list to prevent panic and allow frontend to work
	return []model.User{}, nil
}

// RecommendedPosts is the resolver for the recommendedPosts field.
func (r *queryResolver) RecommendedPosts(ctx context.Context, first int) (*model.PostConnection, error) {
	panic(fmt.Errorf("not implemented: RecommendedPosts - recommendedPosts"))
}

// Followers is the resolver for the followers field.
func (r *queryResolver) Followers(ctx context.Context, userID string, first int, after *string) (*model.UserConnection, error) {
	fmt.Printf("[Gateway] Followers query received for userID: %s\n", userID)

	// Get followers from interaction service
	req := &interaction_proto.GetFollowersRequest{
		UserId:   userID,
		Page:     1, // Start from page 1
		PageSize: int32(first),
	}

	res, err := r.InteractionServiceClient.GetFollowers(ctx, req)
	if err != nil {
		fmt.Printf("[Gateway] Error fetching followers: %v\n", err)
		return nil, fmt.Errorf("failed to fetch followers: %w", err)
	}

	// Convert to GraphQL format
	edges := make([]model.UserEdge, len(res.Followers))
	for i, follower := range res.Followers {
		// Get full user details from user service
		userRes, err := r.UserServiceClient.GetUser(ctx, &user_proto.GetUserRequest{UserId: follower.FollowerId})
		if err != nil {
			fmt.Printf("[Gateway] Error fetching user details for follower %s: %v\n", follower.FollowerId, err)
			continue
		}

		// Check if current user is following this follower
		claims := middleware.GetUserClaims(ctx)
		isFollowing := false
		if claims != nil {
			fmt.Printf("[Gateway] Checking if user %s is following follower %s\n", claims.UserID, follower.FollowerId)
			if claims.UserID == follower.FollowerId {
				// Don't show follow button for self
				isFollowing = false
				fmt.Printf("[Gateway] Follower is self, setting isFollowing=false\n")
			} else {
				// Check if current user follows this follower
				followRes, err := r.InteractionServiceClient.IsFollowing(ctx, &interaction_proto.IsFollowingRequest{
					FollowerId: claims.UserID,
					FolloweeId: follower.FollowerId,
				})
				if err == nil {
					isFollowing = followRes.IsFollowing
					fmt.Printf("[Gateway] IsFollowing result: %v\n", isFollowing)
				} else {
					fmt.Printf("[Gateway] Error checking follow status: %v\n", err)
				}
			}
		}

		edges[i] = model.UserEdge{
			Node: &model.User{
				ID:          userRes.User.Id,
				Username:    userRes.User.Username,
				DisplayName: &userRes.User.DisplayName,
				Bio:         &userRes.User.Bio,
				AvatarURL:   &userRes.User.AvatarUrl,
				IsFollowing: &isFollowing,
				IsVerified:  &userRes.User.IsVerified,
			},
			Cursor: follower.FollowerId, // Use user ID as cursor
		}
	}

	// Calculate pagination info
	hasNextPage := false
	var endCursor *string
	if len(res.Followers) > 0 {
		lastFollower := res.Followers[len(res.Followers)-1]
		endCursor = &lastFollower.FollowerId
		// Simple pagination logic - if we got the full page size, assume there might be more
		hasNextPage = len(res.Followers) == int(req.PageSize)
	}

	return &model.UserConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNextPage,
			EndCursor:   endCursor,
		},
	}, nil
}

// Following is the resolver for the following field.
func (r *queryResolver) Following(ctx context.Context, userID string, first int, after *string) (*model.UserConnection, error) {
	fmt.Printf("[Gateway] Following query received for userID: %s\n", userID)

	// Get following from interaction service
	req := &interaction_proto.GetFollowingRequest{
		UserId:   userID,
		Page:     1, // Start from page 1
		PageSize: int32(first),
	}

	res, err := r.InteractionServiceClient.GetFollowing(ctx, req)
	if err != nil {
		fmt.Printf("[Gateway] Error fetching following: %v\n", err)
		return nil, fmt.Errorf("failed to fetch following: %w", err)
	}

	// Convert to GraphQL format
	edges := make([]model.UserEdge, len(res.Following))
	for i, followee := range res.Following {
		// Get full user details from user service
		userRes, err := r.UserServiceClient.GetUser(ctx, &user_proto.GetUserRequest{UserId: followee.FolloweeId})
		if err != nil {
			fmt.Printf("[Gateway] Error fetching user details for followee %s: %v\n", followee.FolloweeId, err)
			continue
		}

		// Determine follow status based on context
		claims := middleware.GetUserClaims(ctx)
		isFollowing := false

		if claims != nil {
			fmt.Printf("[Gateway] Checking follow status for followee %s, viewer %s, profile owner %s\n", followee.FolloweeId, claims.UserID, userID)
			if claims.UserID == followee.FolloweeId {
				// Don't show follow button for self
				isFollowing = false
				fmt.Printf("[Gateway] Followee is self, setting isFollowing=false\n")
			} else {
				// Check if current user follows this followee
				followRes, err := r.InteractionServiceClient.IsFollowing(ctx, &interaction_proto.IsFollowingRequest{
					FollowerId: claims.UserID,
					FolloweeId: followee.FolloweeId,
				})
				if err == nil {
					isFollowing = followRes.IsFollowing
					fmt.Printf("[Gateway] IsFollowing result: %v\n", isFollowing)
				} else {
					fmt.Printf("[Gateway] Error checking follow status: %v\n", err)
				}
			}
		}

		edges[i] = model.UserEdge{
			Node: &model.User{
				ID:          userRes.User.Id,
				Username:    userRes.User.Username,
				DisplayName: &userRes.User.DisplayName,
				Bio:         &userRes.User.Bio,
				AvatarURL:   &userRes.User.AvatarUrl,
				IsFollowing: &isFollowing,
				IsVerified:  &userRes.User.IsVerified,
			},
			Cursor: followee.FolloweeId, // Use user ID as cursor
		}
	}

	// Calculate pagination info
	hasNextPage := false
	var endCursor *string
	if len(res.Following) > 0 {
		lastFollowee := res.Following[len(res.Following)-1]
		endCursor = &lastFollowee.FolloweeId
		// Simple pagination logic - if we got the full page size, assume there might be more
		hasNextPage = len(res.Following) == int(req.PageSize)
	}

	return &model.UserConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNextPage,
			EndCursor:   endCursor,
		},
	}, nil
}

// UserProfileUpdated is the resolver for the userProfileUpdated field.
func (r *subscriptionResolver) UserProfileUpdated(ctx context.Context, userID string) (<-chan *model.UserProfileUpdateEvent, error) {
	if r.MessageBus == nil {
		return nil, fmt.Errorf("message bus not available")
	}

	// Subscribe to user profile update events
	msgChan, err := r.MessageBus.Subscribe(ctx, messagebus.TopicUserProfileUpdated)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to user profile updates: %w", err)
	}

	// Create output channel for GraphQL subscription
	eventChan := make(chan *model.UserProfileUpdateEvent, 10)

	go func() {
		defer close(eventChan)

		for {
			select {
			case msg, ok := <-msgChan:
				if !ok {
					return
				}

				// Parse the message
				var event messagebus.UserProfileUpdatedEvent
				if err := json.Unmarshal(msg.Data, &event); err != nil {
					fmt.Printf("[GraphQL Subscription] Failed to unmarshal event: %v\n", err)
					continue
				}

				// Filter events for the specific user
				if event.UserID == userID {
					// Convert to GraphQL model
					gqlEvent := &model.UserProfileUpdateEvent{
						UserID:        event.UserID,
						Username:      event.Username,
						DisplayName:   &event.DisplayName,
						AvatarURL:     &event.AvatarURL,
						AvatarVersion: func() *int { v := int(event.AvatarVersion); return &v }(),
						EventType:     event.EventType,
						UpdatedAt:     event.UpdatedAt.Format(time.RFC3339),
					}

					select {
					case eventChan <- gqlEvent:
					case <-ctx.Done():
						return
					}
				}

			case <-ctx.Done():
				return
			}
		}
	}()

	return eventChan, nil
}

// PostCreated is the resolver for the postCreated field.
func (r *subscriptionResolver) PostCreated(ctx context.Context) (<-chan *model.PostCreatedEvent, error) {
	panic(fmt.Errorf("not implemented: PostCreated - postCreated"))
}

// PostUpdated is the resolver for the postUpdated field.
func (r *subscriptionResolver) PostUpdated(ctx context.Context, postID string) (<-chan *model.PostUpdatedEvent, error) {
	panic(fmt.Errorf("not implemented: PostUpdated - postUpdated"))
}

// MediaProcessed is the resolver for the mediaProcessed field.
func (r *subscriptionResolver) MediaProcessed(ctx context.Context, postID string) (<-chan *model.MediaProcessedEvent, error) {
	panic(fmt.Errorf("not implemented: MediaProcessed - mediaProcessed"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
